### ISSUE TITLE
Sync Height Incorrect Value While Downloading

### ISSUE THREAD

**Issue by CryptoDJ** [SCDeveloper/Silk-Release-Candidate#25]
### Describe the issue in detail
The sync height displayed in the peer table display is incorrect while downloading the chain.
### Steps to reproduce
1. Delete block chain files
2. Launch qt wallet
3. Open peer table view
4. Select peer with fully downloaded chain.  The sync value is negative.

### Expected behavior
Sync height should display "Chain downloading" instead of a negative number.

### Actual behavior
Show a negative number.

### What platform are you using (Linux-64, Windows-32, OS X, etc..)
Linux 64-bit.

**Comment by CryptoDJ** [comment]
PR #26 fixes this issue.  Please close after the PR is merged.

**Comment by SCDeveloper** [comment]
Merged
